// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/telegram_logger.proto

package logger

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelegramLogger_SendLog_FullMethodName = "/api.TelegramLogger/SendLog"
)

// TelegramLoggerClient is the client API for TelegramLogger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelegramLoggerClient interface {
	SendLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
}

type telegramLoggerClient struct {
	cc grpc.ClientConnInterface
}

func NewTelegramLoggerClient(cc grpc.ClientConnInterface) TelegramLoggerClient {
	return &telegramLoggerClient{cc}
}

func (c *telegramLoggerClient) SendLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, TelegramLogger_SendLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelegramLoggerServer is the server API for TelegramLogger service.
// All implementations must embed UnimplementedTelegramLoggerServer
// for forward compatibility.
type TelegramLoggerServer interface {
	SendLog(context.Context, *LogRequest) (*LogResponse, error)
	mustEmbedUnimplementedTelegramLoggerServer()
}

// UnimplementedTelegramLoggerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelegramLoggerServer struct{}

func (UnimplementedTelegramLoggerServer) SendLog(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLog not implemented")
}
func (UnimplementedTelegramLoggerServer) mustEmbedUnimplementedTelegramLoggerServer() {}
func (UnimplementedTelegramLoggerServer) testEmbeddedByValue()                        {}

// UnsafeTelegramLoggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelegramLoggerServer will
// result in compilation errors.
type UnsafeTelegramLoggerServer interface {
	mustEmbedUnimplementedTelegramLoggerServer()
}

func RegisterTelegramLoggerServer(s grpc.ServiceRegistrar, srv TelegramLoggerServer) {
	// If the following call pancis, it indicates UnimplementedTelegramLoggerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelegramLogger_ServiceDesc, srv)
}

func _TelegramLogger_SendLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramLoggerServer).SendLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramLogger_SendLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramLoggerServer).SendLog(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelegramLogger_ServiceDesc is the grpc.ServiceDesc for TelegramLogger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelegramLogger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.TelegramLogger",
	HandlerType: (*TelegramLoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendLog",
			Handler:    _TelegramLogger_SendLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/telegram_logger.proto",
}
