// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: api/telegram_logger.proto

package logger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_api_telegram_logger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_telegram_logger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_api_telegram_logger_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *LogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_api_telegram_logger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_telegram_logger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_api_telegram_logger_proto_rawDescGZIP(), []int{1}
}

func (x *LogResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_api_telegram_logger_proto protoreflect.FileDescriptor

const file_api_telegram_logger_proto_rawDesc = "" +
	"\n" +
	"\x19api/telegram_logger.proto\x12\x03api\"L\n" +
	"\n" +
	"LogRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\x1d\n" +
	"\vLogResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2>\n" +
	"\x0eTelegramLogger\x12,\n" +
	"\aSendLog\x12\x0f.api.LogRequest\x1a\x10.api.LogResponseB\x10Z\x0epkg/api/loggerb\x06proto3"

var (
	file_api_telegram_logger_proto_rawDescOnce sync.Once
	file_api_telegram_logger_proto_rawDescData []byte
)

func file_api_telegram_logger_proto_rawDescGZIP() []byte {
	file_api_telegram_logger_proto_rawDescOnce.Do(func() {
		file_api_telegram_logger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_telegram_logger_proto_rawDesc), len(file_api_telegram_logger_proto_rawDesc)))
	})
	return file_api_telegram_logger_proto_rawDescData
}

var file_api_telegram_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_telegram_logger_proto_goTypes = []any{
	(*LogRequest)(nil),  // 0: api.LogRequest
	(*LogResponse)(nil), // 1: api.LogResponse
}
var file_api_telegram_logger_proto_depIdxs = []int32{
	0, // 0: api.TelegramLogger.SendLog:input_type -> api.LogRequest
	1, // 1: api.TelegramLogger.SendLog:output_type -> api.LogResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_telegram_logger_proto_init() }
func file_api_telegram_logger_proto_init() {
	if File_api_telegram_logger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_telegram_logger_proto_rawDesc), len(file_api_telegram_logger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_telegram_logger_proto_goTypes,
		DependencyIndexes: file_api_telegram_logger_proto_depIdxs,
		MessageInfos:      file_api_telegram_logger_proto_msgTypes,
	}.Build()
	File_api_telegram_logger_proto = out.File
	file_api_telegram_logger_proto_goTypes = nil
	file_api_telegram_logger_proto_depIdxs = nil
}
