// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/telegram_logger.proto

package logger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Data          *LogData               `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_api_telegram_logger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_telegram_logger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_api_telegram_logger_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *LogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRequest) GetData() *LogData {
	if x != nil {
		return x.Data
	}
	return nil
}

type LogData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserIp        string                 `protobuf:"bytes,2,opt,name=user_ip,json=userIp,proto3" json:"user_ip,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Time          string                 `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
	Latency       string                 `protobuf:"bytes,7,opt,name=latency,proto3" json:"latency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogData) Reset() {
	*x = LogData{}
	mi := &file_api_telegram_logger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogData) ProtoMessage() {}

func (x *LogData) ProtoReflect() protoreflect.Message {
	mi := &file_api_telegram_logger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogData.ProtoReflect.Descriptor instead.
func (*LogData) Descriptor() ([]byte, []int) {
	return file_api_telegram_logger_proto_rawDescGZIP(), []int{1}
}

func (x *LogData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LogData) GetUserIp() string {
	if x != nil {
		return x.UserIp
	}
	return ""
}

func (x *LogData) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *LogData) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LogData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LogData) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *LogData) GetLatency() string {
	if x != nil {
		return x.Latency
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_api_telegram_logger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_telegram_logger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_api_telegram_logger_proto_rawDescGZIP(), []int{2}
}

func (x *LogResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_api_telegram_logger_proto protoreflect.FileDescriptor

const file_api_telegram_logger_proto_rawDesc = "" +
	"\n" +
	"\x19api/telegram_logger.proto\x12\x03api\"Z\n" +
	"\n" +
	"LogRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12 \n" +
	"\x04data\x18\x03 \x01(\v2\f.api.LogDataR\x04data\"\xad\x01\n" +
	"\aLogData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\auser_ip\x18\x02 \x01(\tR\x06userIp\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x12\n" +
	"\x04time\x18\x06 \x01(\tR\x04time\x12\x18\n" +
	"\alatency\x18\a \x01(\tR\alatency\"\x1d\n" +
	"\vLogResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2>\n" +
	"\x0eTelegramLogger\x12,\n" +
	"\aSendLog\x12\x0f.api.LogRequest\x1a\x10.api.LogResponseB\x10Z\x0epkg/api/loggerb\x06proto3"

var (
	file_api_telegram_logger_proto_rawDescOnce sync.Once
	file_api_telegram_logger_proto_rawDescData []byte
)

func file_api_telegram_logger_proto_rawDescGZIP() []byte {
	file_api_telegram_logger_proto_rawDescOnce.Do(func() {
		file_api_telegram_logger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_telegram_logger_proto_rawDesc), len(file_api_telegram_logger_proto_rawDesc)))
	})
	return file_api_telegram_logger_proto_rawDescData
}

var file_api_telegram_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_telegram_logger_proto_goTypes = []any{
	(*LogRequest)(nil),  // 0: api.LogRequest
	(*LogData)(nil),     // 1: api.LogData
	(*LogResponse)(nil), // 2: api.LogResponse
}
var file_api_telegram_logger_proto_depIdxs = []int32{
	1, // 0: api.LogRequest.data:type_name -> api.LogData
	0, // 1: api.TelegramLogger.SendLog:input_type -> api.LogRequest
	2, // 2: api.TelegramLogger.SendLog:output_type -> api.LogResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_telegram_logger_proto_init() }
func file_api_telegram_logger_proto_init() {
	if File_api_telegram_logger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_telegram_logger_proto_rawDesc), len(file_api_telegram_logger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_telegram_logger_proto_goTypes,
		DependencyIndexes: file_api_telegram_logger_proto_depIdxs,
		MessageInfos:      file_api_telegram_logger_proto_msgTypes,
	}.Build()
	File_api_telegram_logger_proto = out.File
	file_api_telegram_logger_proto_goTypes = nil
	file_api_telegram_logger_proto_depIdxs = nil
}
